USE [master]
GO
/****** Object:  Database [CRM_UiPath]    Script Date: 7/16/2020 3:38:36 PM ******/
CREATE DATABASE [CRM_UiPath]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CRM_UiPath', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CRM_UiPath.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CRM_UiPath_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CRM_UiPath_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [CRM_UiPath] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CRM_UiPath].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CRM_UiPath] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CRM_UiPath] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CRM_UiPath] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CRM_UiPath] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CRM_UiPath] SET ARITHABORT OFF 
GO
ALTER DATABASE [CRM_UiPath] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CRM_UiPath] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CRM_UiPath] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CRM_UiPath] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CRM_UiPath] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CRM_UiPath] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CRM_UiPath] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CRM_UiPath] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CRM_UiPath] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CRM_UiPath] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CRM_UiPath] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CRM_UiPath] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CRM_UiPath] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CRM_UiPath] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CRM_UiPath] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CRM_UiPath] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CRM_UiPath] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CRM_UiPath] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CRM_UiPath] SET  MULTI_USER 
GO
ALTER DATABASE [CRM_UiPath] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CRM_UiPath] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CRM_UiPath] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CRM_UiPath] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CRM_UiPath] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CRM_UiPath] SET QUERY_STORE = OFF
GO
USE [CRM_UiPath]
GO
/****** Object:  Schema [Dictionary]    Script Date: 7/16/2020 3:38:36 PM ******/
CREATE SCHEMA [Dictionary]
GO
/****** Object:  Schema [Users]    Script Date: 7/16/2020 3:38:36 PM ******/
CREATE SCHEMA [Users]
GO
/****** Object:  Table [Dictionary].[Roles]    Script Date: 7/16/2020 3:38:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Dictionary].[Roles](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Role] [nvarchar](50) NOT NULL,
	[Updated] [datetime] NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Users].[Users]    Script Date: 7/16/2020 3:38:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Users].[Users](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](100) NOT NULL,
	[LastName] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[RoleID] [int] NOT NULL,
	[Registered] [datetime] NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [Dictionary].[Roles] ON 
GO
INSERT [Dictionary].[Roles] ([ID], [Role], [Updated], [IsActive]) VALUES (1, N'Admin', CAST(N'2020-07-12T09:09:18.910' AS DateTime), 1)
GO
INSERT [Dictionary].[Roles] ([ID], [Role], [Updated], [IsActive]) VALUES (2, N'Editor', CAST(N'2020-07-12T09:09:36.180' AS DateTime), 1)
GO
SET IDENTITY_INSERT [Dictionary].[Roles] OFF
GO
SET IDENTITY_INSERT [Users].[Users] ON 
GO
INSERT [Users].[Users] ([ID], [FirstName], [LastName], [Email], [RoleID], [Registered], [IsActive]) VALUES (1, N'Federico', N'Navarrete', N'federico@noreply.com', 1, CAST(N'2020-07-12T09:13:18.833' AS DateTime), 1)
GO
INSERT [Users].[Users] ([ID], [FirstName], [LastName], [Email], [RoleID], [Registered], [IsActive]) VALUES (2, N'Marcos', N'Soriano', N'm_soriano@noreply.com', 2, CAST(N'2020-07-12T09:13:42.950' AS DateTime), 1)
GO
INSERT [Users].[Users] ([ID], [FirstName], [LastName], [Email], [RoleID], [Registered], [IsActive]) VALUES (3, N'Maria', N'Alba', N'maria_alba@noreply.com', 2, CAST(N'2020-07-12T09:14:17.510' AS DateTime), 1)
GO
SET IDENTITY_INSERT [Users].[Users] OFF
GO
ALTER TABLE [Dictionary].[Roles] ADD  CONSTRAINT [DF_Roles_Updated]  DEFAULT (getdate()) FOR [Updated]
GO
ALTER TABLE [Dictionary].[Roles] ADD  CONSTRAINT [DF_Roles_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [Users].[Users] ADD  CONSTRAINT [DF_Users_Registered]  DEFAULT (getdate()) FOR [Registered]
GO
ALTER TABLE [Users].[Users] ADD  CONSTRAINT [DF_Users_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [Users].[Users]  WITH CHECK ADD  CONSTRAINT [FK_Users_Roles] FOREIGN KEY([RoleID])
REFERENCES [Dictionary].[Roles] ([ID])
GO
ALTER TABLE [Users].[Users] CHECK CONSTRAINT [FK_Users_Roles]
GO
USE [master]
GO
ALTER DATABASE [CRM_UiPath] SET  READ_WRITE 
GO
